version: '3'
services:
  #CONTAINER DO BANCO DE DADOS
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - microservices:/var/lib/mysql

  #CONTAINER DO SERVIÇO DE SEGURANCA DE USUARIO
  usersecurity:
    build:
      context: ./ws-usersecurity
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
  
  #CONTAINER DO SERVIÇO MODEL 
  model:
    build:
      context: ./ws-model
      dockerfile: Dockerfile
    ports:
      - "8083:8083"

volumes:
  microservices:
