web: java -Dserver.port=$PORT -Dspring.profiles.active=prod $JAVA_OPTS -jar target/usersecurity-0.0.1-SNAPSHOT.jar

web: java $JAVA_OPTS -Dserver.port=$PORT -jar target/*.jar --spring.config.location=classpath:heroku-db.properties
